language: ruby
rvm:
    - 2.0.0
script:
    - RAILS_ENV=test bundle exec rake db:setup --trace
    - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
branches:
    only:
        - master
before_install:
    - sudo apt-get install -qq openjdk-6-jre
env:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql
before_script:
    - cp config/database.travis.yml config/database.yml
    - mysql -e 'create database sngtrkr_test_db'
    - psql -c 'create database sngtrkr_test_db' -U postgres