# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: true
:concurrency: 25
:queues:
  - [artists, 10]
  - [releases, 10]