production:
  solr:
    hostname: localhost
    port: 8080 #tomcat defaults to port 8080
    path: '/solr'
    log_level: WARNING
  auto_commit_after_delete_request: true
development:
  solr:
    hostname: localhost
    port: 8080 #tomcat defaults to port 8080
    path: '/solr'
    log_level: INFO
  auto_commit_after_delete_request: true
test:
  solr:
    hostname: localhost
    port: 8080 #tomcat defaults to port 8080
    path: '/solr'
    log_level: WARNING
  auto_commit_after_delete_request: true