development:
  solr:
    hostname: localhost
    port: 8980
    log_level: INFO
  auto_commit_after_delete_request: true

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: OFF

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /var/www/sngtrkr/shared/solr
    solr_home: /var/www/sngtrkr/current
    max_memory: 100MB
  auto_commit_after_request: true  